
-- Task 4. Subquery and its type:
-- 1. Write an SQL query to find out which customers have not placed any orders.
select firstname, lastname, customerid from customers 
where CustomerId not in (select CustomerId from orders);

-- 2. Write an SQL query to find the total number of products available for sale.
select count(*) as totalnumber from products;
select (select count(*) from products) as TotalNumberOfProducts;

-- 3.  Write an SQL query to calculate the total revenue generated by TechShop.
select sum(totalamount) from orders;
select (select sum(TotalAmount) from orders) as TotalRevenue;

-- 4. Write an SQL query to calculate the average quantity ordered for products in a specific category.
select Catogories from products;
select avg(quantity) from orderdetails
where ProductId in (select productid from products where Catogories="electronicaccessories");

-- 5. Write an SQL query to calculate the total revenue generated by a specific customer.
select sum(totalamount) from orders where CustomerId=3;

-- 6. Write an SQL query to find the customers who have placed the most orders. List their names and the number of orders they've placed.
select CustomerId,FirstName,LastName,(select count(*) from orders o where o.CustomerId=c.CustomerId) as OrderCount
from customers c where(select count(*) from orders o where o.CustomerId=c.CustomerId)=
(select max(OrderCount) from(select CustomerId,count(*) as OrderCount from orders group by CustomerId) as orderCount);

-- 7. Write an SQL query to find the most popular product category, which is the one with the highest total quantity ordered across all orders.
select productName from Products where ProductId = (select ProductId from OrderDetails group by ProductId having sum(Quantity)=(select max(TotalQty)
from(select ProductId, sum(Quantity) as TotalQty from OrderDetails group by ProductId) as QuantityPerProduct));

-- 8. Write an SQL query to find the customer who has spent the most money (highest total revenue) on electronic gadgets.


-- 9. Write an SQL query to calculate the average order value (total revenue divided by the number of orders) for all customers.
select(select sum(TotalAmount) / count(OrderId) from orders) as AvgOrderValue;

-- 10. Write an SQL query to find the total number of orders placed by each customer and list their names along with the order count.
select c.CustomerId,c.FirstName,c.LastName,(select count(o.OrderId) from orders o where o.CustomerId=c.CustomerId) as TotalNumberOfOrders from customers c;

